language: python
sudo: true
dist: focal

addons:
  apt:
    packages:
    - pkg-config
    - g++
    - gfortran
    - bison
    - flex
    - libexpat1-dev
    - fftw3-dev
    - autoconf
    - automake
    - libtool
    - build-essential
    - pgplot5
    - subversion
    - libgsl-dev
    - libopenmpi-dev
    - openmpi-bin

python:
  - 2.7

matrix:
  fast_finish: true
  allow_failures:
  - python: 2.7  # without ipp
  include:
  - python: 2.7
    env: TRAVIS_IPP=TRUE
  - python: 2.7

git:
  depth: 99999

install:
  - . travis-ipp.bash
  # copy these because running them from setup/ does not work
  - cp setup/setup.bash .
  - cp setup/install-difx .
  - cp setup/genipppc .

  - DIFXROOT_OVERRIDE=$PWD . setup.bash
  - python install-difx $IPPARG

script:
  - /bin/true
